---
title: "this is for the result part of the draft"
author: "Wei Wang"
date: 2017-03-15
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

## data analysis on the normalized data

### missing data imputation

#### Tumors data

click here [Tumor data](MissingTumor.html) to check my result

#### Movie data 

click here 

### gene expression data

## further issues

### NMF

### tensor flash


## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
