---
title: "Home"
output:
  html_document:
    toc: false
---

### simulation studies

### Orthogonal CV

Click on this [orthogonal CV](miss_position.html) to see my example.

Click on this [Questions on Algorithm](first-analysis.html) to see more details.

### flash on the chipseq data from Kevin

Click on this [three data sets on the 4500 rows chr1 var_col](sd_chr1_asinh.html) to see more details.

[ns](draft.html) 

Click on this [load reslut of GTEx data](GTExresult.html) to see more details.

Click on this [pairwise plot](pairwiseplotofflashgtexzscore.html) to see more details.

### Issues

Click on this [gap issue](ObjGap.html) to see more details. (test)


Click on this [summary of the rank0 vs rank1](Obj_summary.html) to see a simple summary to the following two items.

- Click on this [rank 0 vs rank 1](Objcheck_1.html) to see more details.
- Click on this [rank 0 vs rank 1: fdr with penalty](Objcheck_2.html) to see more details.

## flashr2

This is a simple test [first try](flash_beta_test.html)

Initialization issue: [softimpute as initialization](missingimputeinitial.html)

Click here to find the [null check for flashr2](NULLcheck.html) and [densen nu case](nullcheck2.html)

### apply flashr2 for the examples in FLASH paper

#### simulations

Click here to check the [simulatoin result (rank one and rank three)](applyflahr2onsimulations.html)

#### GTEx Z-score

Here is a example to run `flashr2` on RCC [RCC template](GTEXzscoreTemplate.html)

#### missing data imputation

click here to check the template for [missing data imputation with OCV](templateforOCV.html)

click here to check the comparison of different options for FLASH [different shrink options](compareOptionsOCV.Rmd)
