---
title: "NUll check for flashr2"
author: "Wei Wang"
date: 09-17
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->


```{r}
library(flashr2)
library(MASS)
```

## model

In this case the data sets are:
$$H_0: X \sim N(0, \Sigma_0)$$
$$H_1: X \sim N(0,\Sigma_1)$$
where $\Sigma_0 = I$ and $\Sigma_1 = I + \nu \nu^T$



### dense case 

```{r}
########  spiked covariance model

set.seed(99)
T = 300
lambda_0 = rep(NA,T)
flash2_rank_0= rep(1,T)
for(t in 1:T){
  P = 300
  N = 100
  Sigma_0 = diag(rep(1,P))
  X = mvrnorm(n = N,mu = rep(0,P), Sigma = Sigma_0)
  X = X/sqrt(mean((X)^2))
  lambda_0[t] =  svd(X)$d[1]
  data =  flashr2::flash_set_data(X)
  g1= flashr2::flash_r1(data,verbose=F)
  if(sum(g1$EL) ==0 )  {flash2_rank_0[t] = 0}
}

set.seed(99)
lambda_1 = rep(NA,T)
flash2_rank_1= rep(1,T)
for(t in 1:T){
  P = 300
  N = 100
  Sigma_0 = diag(rep(1,P))
  nu = rnorm(P, 0, (2)/(sqrt(P)))
  # index_nu = sample(seq(1:P),(P*0.95))
  # nu[index_nu] = 0
  Sigma_1 = Sigma_0 + nu %*% t(nu)
  X = mvrnorm(n = N,mu = rep(0,P), Sigma = Sigma_1)
  X = X/sqrt(mean((X)^2))
  lambda_1[t] =  svd(X)$d[1]
  data = flashr2::flash_set_data(X)
  g1= flashr2::flash_r1(data,verbose=F)
  if(sum(g1$EL) ==0 )  {flash2_rank_1[t] = 0}
}



lambda_0_0 = lambda_0[which(flash2_rank_0 ==0)]
lambda_0_1 = lambda_0[which(flash2_rank_0 ==1)]


lambda_1_0 = lambda_1[which(flash2_rank_1 ==0)]
lambda_1_1 = lambda_1[which(flash2_rank_1 ==1)]

simple_roc <- function(labels, scores){
  labels <- labels[order(scores, decreasing=TRUE)]
  data.frame(TPR=cumsum(labels)/sum(labels), FPR=cumsum(!labels)/sum(!labels), labels)
}

lambda.roc = simple_roc(labels = c(rep(0,T),rep(1,T)),scores = c(lambda_0,lambda_1))
plot(lambda.roc$FPR,lambda.roc$TPR,type = "l",col = "black")
flash.roc = simple_roc(labels = c(rep(0,T),rep(1,T)),scores = c(flash2_rank_0,flash2_rank_1))
lines(flash.roc$FPR,flash.roc$TPR,type = "l",col = "red")
```



### sparse case

```{r}
########  spiked covariance model

set.seed(99)
T = 300
lambda_0 = rep(NA,T)
flash2_rank_0= rep(1,T)
for(t in 1:T){
  P = 300
  N = 100
  Sigma_0 = diag(rep(1,P))
  X = mvrnorm(n = N,mu = rep(0,P), Sigma = Sigma_0)
  X = X/sqrt(mean((X)^2))
  lambda_0[t] =  svd(X)$d[1]
  data =  flashr2::flash_set_data(X)
  g1= flashr2::flash_r1(data,verbose=F)
  if(sum(g1$EL) ==0 )  {flash2_rank_0[t] = 0}
}

set.seed(99)
lambda_1 = rep(NA,T)
flash2_rank_1= rep(1,T)
for(t in 1:T){
  P = 300
  N = 100
  Sigma_0 = diag(rep(1,P))
  nu = rnorm(P, 0, (6)/(sqrt(P)))
  index_nu = sample(seq(1:P),(P*0.95))
  nu[index_nu] = 0
  Sigma_1 = Sigma_0 + nu %*% t(nu)
  X = mvrnorm(n = N,mu = rep(0,P), Sigma = Sigma_1)
  X = X/sqrt(mean((X)^2))
  lambda_1[t] =  svd(X)$d[1]
  data = flashr2::flash_set_data(X)
  g1= flashr2::flash_r1(data,verbose=F)
  if(sum(g1$EL) ==0 )  {flash2_rank_1[t] = 0}
}



lambda_0_0 = lambda_0[which(flash2_rank_0 ==0)]
lambda_0_1 = lambda_0[which(flash2_rank_0 ==1)]


lambda_1_0 = lambda_1[which(flash2_rank_1 ==0)]
lambda_1_1 = lambda_1[which(flash2_rank_1 ==1)]

simple_roc <- function(labels, scores){
  labels <- labels[order(scores, decreasing=TRUE)]
  data.frame(TPR=cumsum(labels)/sum(labels), FPR=cumsum(!labels)/sum(!labels), labels)
}

lambda.roc = simple_roc(labels = c(rep(0,T),rep(1,T)),scores = c(lambda_0,lambda_1))
plot(lambda.roc$FPR,lambda.roc$TPR,type = "l",col = "black")
flash.roc = simple_roc(labels = c(rep(0,T),rep(1,T)),scores = c(flash2_rank_0,flash2_rank_1))
lines(flash.roc$FPR,flash.roc$TPR,type = "l",col = "red")
```


## likelihood ratio


## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
