---
title: "null check for flashr2"
author: "wei"
date: 09-16
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

```{r}
library(flashr2)
library(MASS)
```

```{r}
########  spiked covariance model

set.seed(99)
T = 1000
lambda_0 = rep(NA,T)
flash_rank_0= rep(1,T)
flash2_rank_0= rep(1,T)
for(t in 1:T){
  P = 300
  N = 100
  Sigma_0 = diag(rep(1,P))
  X = mvrnorm(n = N,mu = rep(0,P), Sigma = Sigma_0)
  lambda_0[t] =  svd(X)$d[1]
  data = set_flash_data(X)
  g1= flash_r1(data,verbose=F)
  g2 = flashr::flash(X)
  if(sum(g1$EL) ==0 )  {flash2_rank_0[t] = 0}
  if(sum(g2$l) ==0 )  {flash_rank_0[t] = 0}
}

set.seed(99)
T = 1000
lambda_1 = rep(NA,T)
flash_rank_1= rep(1,T)
flash2_rank_1= rep(1,T)
for(t in 1:T){
  P = 300
  N = 100
  Sigma_0 = diag(rep(1,P))
  nu = rnorm(P, 0, (6)/(sqrt(P)))
  index_nu = sample(seq(1:P),(P*0.95))
  nu[index_nu] = 0
  Sigma_1 = Sigma_0 + nu %*% t(nu)
  X = mvrnorm(n = N,mu = rep(0,P), Sigma = Sigma_1)
  lambda_1[t] =  svd(X)$d[1]
  data = set_flash_data(X)
  g1= flash_r1(data,verbose=F)
  g2 = flashr::flash(X)
  if(sum(g1$EL) ==0 )  {flash2_rank_1[t] = 0}
  if(sum(g2$l) ==0 )  {flash_rank_1[t] = 0}
}


lambda_1_0_0 = lambda_0[which(flash_rank_0 ==0)]
lambda_1_0_1 = lambda_0[which(flash_rank_0 ==1)]
lambda_2_0_0 = lambda_0[which(flash2_rank_0 ==0)]
lambda_2_0_1 = lambda_0[which(flash2_rank_0 ==1)]

lambda_1_1_0 = lambda_1[which(flash_rank_1 ==0)]
lambda_1_1_1 = lambda_1[which(flash_rank_1 ==1)]
lambda_2_1_0 = lambda_1[which(flash2_rank_1 ==0)]
lambda_2_1_1 = lambda_1[which(flash2_rank_1 ==1)]

```


## model

In this case the data sets are:
$$H_0: X \sim N(0, \Sigma_0)$$
$$H_1: X \sim N(0,\Sigma_1)$$
where $\Sigma_0 = I$ and $\Sigma_1 = I + \nu \nu^T$

```{r}
library(ggplot2)
dat = data.frame(lambda = c(lambda_0,lambda_1), name = c(rep("null",length(lambda_0)), rep("alt", length(lambda_1)) ))
ggplot(dat,aes(x=lambda)) +
  geom_histogram(data=subset(dat,name == 'null'),fill = "red", alpha = 0.2) +
  geom_histogram(data=subset(dat,name == 'alt'),fill = "green", alpha = 0.2) 
```

* red: null
* green: alternative

### flashr

```{r}
library(ggplot2)
dat = data.frame(lambda = c(lambda_1_0_0,lambda_1_0_1,lambda_1_1_0,lambda_1_1_1), 
                 name = c(rep("null 0",length(lambda_1_0_0)),
                          rep("null 1",length(lambda_1_0_1)),
                          rep("alt 0",length(lambda_1_1_0)),
                          rep("alt 1",length(lambda_1_1_1))))
ggplot(dat,aes(x=lambda)) +
  geom_histogram(data=subset(dat,name == 'null 0'),fill = "red", alpha = 0.2) +
  geom_histogram(data=subset(dat,name == 'null 1'),fill = "black", alpha = 0.2) +
  geom_histogram(data=subset(dat,name == 'alt 0'),fill = "blue", alpha = 0.2) +
  geom_histogram(data=subset(dat,name == 'alt 1'),fill = "green", alpha = 0.2)

```

* red: null as rank 0
* black: null as rank 1
* blue: alternative as 0
* green: alternative as 1



### flashr2

```{r}
library(ggplot2)
dat2 = data.frame(lambda = c(lambda_2_0_0,lambda_2_0_1,lambda_2_1_0,lambda_2_1_1), 
                 name = c(rep("null 0",length(lambda_2_0_0)),
                          rep("null 1",length(lambda_2_0_1)),
                          rep("alt 0",length(lambda_2_1_0)),
                          rep("alt 1",length(lambda_2_1_1))))
ggplot(dat,aes(x=lambda)) +
  geom_histogram(data=subset(dat2,name == 'null 0'),fill = "red", alpha = 0.2) +
  geom_histogram(data=subset(dat2,name == 'null 1'),fill = "black", alpha = 0.2) +
  geom_histogram(data=subset(dat2,name == 'alt 0'),fill = "blue", alpha = 0.2) +
  geom_histogram(data=subset(dat2,name == 'alt 1'),fill = "green", alpha = 0.2)

```


* red: null as rank 0
* black: null as rank 1
* blue: alternative as 0
* green: alternative as 1

## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
