---
title: "'gap' issue"
author: "Wei Wang"
date: 
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->

## introduction of the problem.

In the old code of flash. we found that the greedy algorithm 

### old version documnt

The old version document is in `ash-sfa` git repo [ash-sfa repo](https://github.com/stephenslab/ash-sfa).

In the document, we have several observations:




## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
